### ISSUE TITLE
do have any reference for the traditional mutual information method which you have computed?

### ISSUE THREAD

**Issue by asgsaeid** [MasanoriYamada/Mine_pytorch#1]

**Comment by MasanoriYamada** [comment]
@cvdeep I used this

https://mlmeetsdigcomm.wordpress.com/2018/01/24/mutual-information-estimation-from-samples-via-optimization/

**Comment by MasanoriYamada** [comment]
@cvdeep I write note

<img width="797" alt="image" src="https://user-images.githubusercontent.com/8328986/47701408-05ab9400-dc5d-11e8-89ff-82f1b6a45018.png">
